### ISSUE TITLE
数据库那三个表具体信息

### ISSUE THREAD

**Issue by yueyus** [Usernamesisnotavailable/Su-Face-Recognition#1]
数据库中已创建表user、admin、warn表，名，类型，长度之类的都有什么要求吗

**Comment by NGC2237-Nebula** [comment]
可以参考项目中的 init.py 文件。
init.py&nbsp;文件的功能就是自动创建 user、admin、warn 表。三个表的表名，字段类型、长度等参数在SQL语句里面都有说明。
当然也可以直接运行该文件，它能够自动创建三个表并插入初始数据。











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Usernamesisnotavailable/Su-Face-Recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 下午5:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Usernamesisnotavailable/Su-Face-Recognition]数据库那三个表具体信息 (Issue #1)





 
数据库中已创建表user、admin、warn表，名，类型，长度之类的都有什么要求吗

**Comment by yueyus** [comment]
(1273, "Unknown collation: 'utf8mb4_0900_ai_ci'")
(1273, "Unknown collation: 'utf8mb4_0900_ai_ci'")
(1273, "Unknown collation: 'utf8mb4_0900_ai_ci'")
(1146, "Table 'contest.admin' doesn't exist")

**Comment by yueyus** [comment]
我下载dlib==19.24.0一直报错，目前用的是19.19.0，运行main.py会报错AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)，可以分享一下你是如何安装成功的吗

**Comment by NGC2237-Nebula** [comment]
嗯嗯，我的python环境是3.9的，一开始下载dlib是根据这篇博客&nbsp;【Python】dlib 无需编译安装 dlib-19.23.0-cp39-cp39-win_amd64.whl_安装face_recognition-CSDN博客&nbsp;来的，你可以参考一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Usernamesisnotavailable/Su-Face-Recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Usernamesisnotavailable/Su-Face-Recognition] 数据库那三个表具体信息 (Issue #1)





 
我下载dlib==19.24.0一直报错，目前用的是19.19.0，运行main.py会报错AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)，可以分享一下你是如何安装成功的吗
